AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for LLM Pipeline Automation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 4096
    Environment:
        Variables:
          HOST: 34.207.156.26
          DATABASE: postgres
          USER: postgres
          PASSWORD: utemia
          COLLECTION_NAME: utemia_collection
          CHAT_HISTORY_MESSAGE_COUNT: 24

Resources:
  GenerateResponse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Backend
      Handler: Lambda_Response_App.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        Login:
          Type: Api
          Properties:
            Path: /response
            Method: POST
      EphemeralStorage:
        Size: 2048
      Description: "Lee datos de PlSQL RDS y envía una respuesta a la consulta del usuario. Admite historial de chat."